site_name: cookiecutter-pytorch-pl-tb
site_description: Minimal Cookiecutter template for authoring pytorch-pytorchlightning-tensorboard.
site_author: Oh-hyeon Choung

theme: readthedocs

repo_url: https://github.com/Ohyeon5/cookiecutter-pytorch-pl-tb

pages:
- Home: index.md
- User Guide:
    - Quickstart: user-guide/quickstart.md
    - Publish: user-guide/publish-plugin.md
- Contributor Guide:
    - Quickstart: contributor-guide/quickstart.md
    - Documentation: contributor-guide/documentation.md
